# Generated by Django 6.0.6 on 2026-07-17 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='scorer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Live', 'Live'), ('Completed', 'Completed')], default='Upcoming', max_length=20),
        ),
        migrations.CreateModel(
            name='LiveMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('balls', models.PositiveIntegerField(default=0)),
                ('over_history', models.CharField(blank=True, default='', max_length=200)),
                ('innings', models.PositiveIntegerField(default=1)),
                ('team1_target', models.PositiveIntegerField(default=0)),
                ('partnership_runs', models.PositiveIntegerField(default=0)),
                ('partnership_balls', models.PositiveIntegerField(default=0)),
                ('is_free_hit', models.BooleanField(default=False)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_battings', to='tournament.team')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_bowlings', to='tournament.team')),
                ('current_bowler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_bowler', to='tournament.player')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_state', to='tournament.match')),
                ('non_striker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_non_striker', to='tournament.player')),
                ('striker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_striker', to='tournament.player')),
            ],
            options={
                'verbose_name': 'Live Match State',
            },
        ),
    ]
